apiVersion: template.openshift.io/v1
kind: Template
parameters:
- description: The session secret for the component.
  name: SESSION_SECRET
  generate: expression
  from: "[a-zA-Z0-9]{43}"
- description: "The namespace. Must come from a var or it will get stripped off"
  name: NAMESPACE
  value: vega
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: apiserver

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: apiserver-calculations
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: calculations-access
  subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: vega

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: apiserver-endpoints
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: endpoints-access
  subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: vega

- apiVersion: v1
  kind: Service
  metadata:
    namespace: vega
    name: apiserver
    labels:
      app: apiserver
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: apiserver-tls
  spec:
    selector:
      app: apiserver
    ports:
    - name: main
      port: 8080
    type: ClusterIP

- apiVersion: v1
  kind: Secret
  metadata:
    namespace: ${NAMESPACE}
    name: apiserver-session-secret
  stringData:
    session_secret: "${SESSION_SECRET}="

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: apiserver
    labels:
      app: apiserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: apiserver
    template:
      metadata:
        labels:
          app: apiserver
      spec:
        serviceAccount: apiserver
        serviceAccountName: apiserver        
        updateStrategy:
          type: RollingUpdate
        containers:
        - name: oauth-proxy
          image: quay.io/openshift/origin-oauth-proxy@sha256:82719931600d90a8c3eb26b1632cc99020bc12921fa6ad13c9d4929fe2d0f025
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8443
            name: web
          args:
          - -provider=openshift
          - -https-address=:8443
          - -http-address=
          - -email-domain=*
          - -upstream=http://localhost:8080
          - -client-id=system:serviceaccount:vega:apiserver
          - -openshift-ca=/etc/pki/tls/cert.pem
          - -openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - '-openshift-sar={"verb": "get", "resource": "secrets", "namespace": "vega"}'
          - '-openshift-delegate-urls={"/": {"verb": "get", "resource": "secrets", "namespace": "vega"}}'
          - -client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token
          - -cookie-secret-file=/etc/proxy/secrets/session_secret
          - -cookie-samesite=none
          - -tls-cert=/etc/tls/private/tls.crt
          - -tls-key=/etc/tls/private/tls.key
          volumeMounts:
          - mountPath: /etc/tls/private
            name: apiserver-tls
          - mountPath: /etc/proxy/secrets
            name: session-secret
        - name: apiserver
          image: ghcr.io/vega-project/vega-project/ccb-operator/apiserver:latest
          args:
          - --dry-run=false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            timeoutSeconds: 3
            periodSeconds: 3
        volumes:
        - name: apiserver-tls
          secret:
            secretName: apiserver-tls
        - name: session-secret
          secret:
            secretName: apiserver-session-secret
