kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: apiserver

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: apiserver-calculations
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: calculations-access
  subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: vega

- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: apiserver-endpoints
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: endpoints-access
  subjects:
  - kind: ServiceAccount
    name: apiserver
    namespace: vega

- apiVersion: v1
  kind: Service
  metadata:
    namespace: vega
    name: apiserver
    labels:
      app: apiserver
  spec:
    selector:
      app: apiserver
    ports:
    - name: main
      port: 8080
    type: ClusterIP

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: apiserver
    labels:
      app: apiserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: apiserver
    template:
      metadata:
        labels:
          app: apiserver
      spec:
        serviceAccount: apiserver
        serviceAccountName: apiserver        
        updateStrategy:
          type: RollingUpdate
        containers:
        - name: apiserver
          image: ghcr.io/vega-project/vega-project/ccb-operator/apiserver:latest
          args:
          - --dry-run=false
