//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	calculationsv1 "github.com/vega-project/ccb-operator/pkg/apis/calculations/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculationBulkFactory) DeepCopyInto(out *CalculationBulkFactory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.InputFiles != nil {
		in, out := &in.InputFiles, &out.InputFiles
		*out = new(calculationsv1.InputFiles)
		(*in).DeepCopyInto(*out)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculationBulkFactory.
func (in *CalculationBulkFactory) DeepCopy() *CalculationBulkFactory {
	if in == nil {
		return nil
	}
	out := new(CalculationBulkFactory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalculationBulkFactory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculationBulkFactoryList) DeepCopyInto(out *CalculationBulkFactoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CalculationBulkFactory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculationBulkFactoryList.
func (in *CalculationBulkFactoryList) DeepCopy() *CalculationBulkFactoryList {
	if in == nil {
		return nil
	}
	out := new(CalculationBulkFactoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalculationBulkFactoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculationBulkFactoryStatus) DeepCopyInto(out *CalculationBulkFactoryStatus) {
	*out = *in
	in.CreatedTime.DeepCopyInto(&out.CreatedTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculationBulkFactoryStatus.
func (in *CalculationBulkFactoryStatus) DeepCopy() *CalculationBulkFactoryStatus {
	if in == nil {
		return nil
	}
	out := new(CalculationBulkFactoryStatus)
	in.DeepCopyInto(out)
	return out
}
