apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      serviceAccount: dispatcher
      serviceAccountName: dispatcher
      containers:
      - name: dispatcher
        image: ghcr.io/vega-project/vega-project/ccb-operator/dispatcher:latest
        commands: /usr/bin/dispatcher
        args:
          - --namespace=vega
          - --dry-run=false
        volumeMounts:
        - mountPath: /var/tmp/nfs
          name: calculations
      volumes:
      - name: calculations
        persistentVolumeClaim:
          claimName: results-nfs-claim