apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  labels:
    app: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      serviceAccount: dispatcher
      serviceAccountName: dispatcher
      containers:
      - name: dispatcher
        image: ghcr.io/vega-project/vega-project/ccb-operator/dispatcher:latest
        commands: /usr/bin/dispatcher
        args:
          - --namespace=vega
          - --redis-url=redis:6379
          - --redis-password-file=/etc/redis/database-password
        volumeMounts:
          - mountPath: /etc/redis
            name: redis
      volumes:
        - name: redis
          secret:
            secretName: redis
