apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vega-worker
spec:
  selector:
      matchLabels:
        name: vega-worker
  template:
    metadata:
      labels:
        name: vega-worker 
    spec:
      nodeSelector: 
        node-role.kubernetes.io/vega-worker: "true"
      containers:
      - image: ghcr.io/vega-project/vega-project/ccb-operator/worker:latest
        imagePullPolicy: Always
        name: vega-worker
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName        
        commands: 
          - /usr/bin/worker
        args:
          - --kuruz-model-template-file=kurucz_model_file_template.mod
          - --synspec-input-template-file=input_tlusty_fortfive_template
          - --dry-run=false
          - --nodename=$(NODENAME)
        volumeMounts:
        - mountPath: /var/tmp/nfs
          name: calculations
      volumes:
      - name: calculations
        persistentVolumeClaim:
          claimName: results-nfs-claim          
        terminationMessagePath: /dev/termination-log
      serviceAccount: vega-worker
      terminationGracePeriodSeconds: 10
