kind: List
apiVersion: v1
items:
- kind: ClusterRoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: ci-admins-calculations
  subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: cluster-admins
  roleRef:
    kind: ClusterRole
    apiGroup: rbac.authorization.k8s.io
    name: calculations-access
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: calculations-access
  rules:
    - apiGroups:
        - "vega.io"
      resources:
        - calculations
      verbs:
        - get
        - list
        - create
        - delete
        - update
        - patch
        - watch
- kind: ClusterRole
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: endpoints-access
  rules:
    - apiGroups:
        - ""
      resources:
        - endpoints
      verbs:
        - get
        - list
        - create
        - delete
        - update
        - patch
        - watch

