apiVersion: v1
kind: PersistentVolume
metadata:
  name: results-nfs 
spec:
  capacity:
    storage: 100Gi 
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /nfs
    server: 10.0.3.29
  persistentVolumeReclaimPolicy: Retain 