/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	calculationsv1 "gitlab.physics.muni.cz/vega-project/ccb-operator/pkg/apis/calculations/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCalculations implements CalculationInterface
type FakeCalculations struct {
	Fake *FakeCalculationsV1
}

var calculationsResource = schema.GroupVersionResource{Group: "calculations.vega.io", Version: "v1", Resource: "calculations"}

var calculationsKind = schema.GroupVersionKind{Group: "calculations.vega.io", Version: "v1", Kind: "Calculation"}

// Get takes name of the calculation, and returns the corresponding calculation object, and an error if there is any.
func (c *FakeCalculations) Get(name string, options v1.GetOptions) (result *calculationsv1.Calculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(calculationsResource, name), &calculationsv1.Calculation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*calculationsv1.Calculation), err
}

// List takes label and field selectors, and returns the list of Calculations that match those selectors.
func (c *FakeCalculations) List(opts v1.ListOptions) (result *calculationsv1.CalculationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(calculationsResource, calculationsKind, opts), &calculationsv1.CalculationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &calculationsv1.CalculationList{ListMeta: obj.(*calculationsv1.CalculationList).ListMeta}
	for _, item := range obj.(*calculationsv1.CalculationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested calculations.
func (c *FakeCalculations) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(calculationsResource, opts))
}

// Create takes the representation of a calculation and creates it.  Returns the server's representation of the calculation, and an error, if there is any.
func (c *FakeCalculations) Create(calculation *calculationsv1.Calculation) (result *calculationsv1.Calculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(calculationsResource, calculation), &calculationsv1.Calculation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*calculationsv1.Calculation), err
}

// Update takes the representation of a calculation and updates it. Returns the server's representation of the calculation, and an error, if there is any.
func (c *FakeCalculations) Update(calculation *calculationsv1.Calculation) (result *calculationsv1.Calculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(calculationsResource, calculation), &calculationsv1.Calculation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*calculationsv1.Calculation), err
}

// Delete takes name of the calculation and deletes it. Returns an error if one occurs.
func (c *FakeCalculations) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(calculationsResource, name), &calculationsv1.Calculation{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCalculations) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(calculationsResource, listOptions)

	_, err := c.Fake.Invokes(action, &calculationsv1.CalculationList{})
	return err
}

// Patch applies the patch and returns the patched calculation.
func (c *FakeCalculations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *calculationsv1.Calculation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(calculationsResource, name, pt, data, subresources...), &calculationsv1.Calculation{})
	if obj == nil {
		return nil, err
	}
	return obj.(*calculationsv1.Calculation), err
}
