//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	calculationsv1 "github.com/vega-project/ccb-operator/pkg/apis/calculations/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Calculation) DeepCopyInto(out *Calculation) {
	*out = *in
	out.Params = in.Params
	if in.Steps != nil {
		in, out := &in.Steps, &out.Steps
		*out = make([]calculationsv1.Step, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InputFiles != nil {
		in, out := &in.InputFiles, &out.InputFiles
		*out = new(calculationsv1.InputFiles)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Calculation.
func (in *Calculation) DeepCopy() *Calculation {
	if in == nil {
		return nil
	}
	out := new(Calculation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculationBulk) DeepCopyInto(out *CalculationBulk) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.InputFiles != nil {
		in, out := &in.InputFiles, &out.InputFiles
		*out = new(calculationsv1.InputFiles)
		(*in).DeepCopyInto(*out)
	}
	if in.Calculations != nil {
		in, out := &in.Calculations, &out.Calculations
		*out = make(map[string]Calculation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.PostCalculation != nil {
		in, out := &in.PostCalculation, &out.PostCalculation
		*out = new(Calculation)
		(*in).DeepCopyInto(*out)
	}
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculationBulk.
func (in *CalculationBulk) DeepCopy() *CalculationBulk {
	if in == nil {
		return nil
	}
	out := new(CalculationBulk)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalculationBulk) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculationBulkList) DeepCopyInto(out *CalculationBulkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CalculationBulk, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculationBulkList.
func (in *CalculationBulkList) DeepCopy() *CalculationBulkList {
	if in == nil {
		return nil
	}
	out := new(CalculationBulkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CalculationBulkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CalculationBulkStatus) DeepCopyInto(out *CalculationBulkStatus) {
	*out = *in
	in.CreatedTime.DeepCopyInto(&out.CreatedTime)
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CalculationBulkStatus.
func (in *CalculationBulkStatus) DeepCopy() *CalculationBulkStatus {
	if in == nil {
		return nil
	}
	out := new(CalculationBulkStatus)
	in.DeepCopyInto(out)
	return out
}
