/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"time"

	v1 "gitlab.physics.muni.cz/vega-project/ccb-operator/pkg/apis/calculations/v1"
	scheme "gitlab.physics.muni.cz/vega-project/ccb-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CalculationsGetter has a method to return a CalculationInterface.
// A group's client should implement this interface.
type CalculationsGetter interface {
	Calculations() CalculationInterface
}

// CalculationInterface has methods to work with Calculation resources.
type CalculationInterface interface {
	Create(*v1.Calculation) (*v1.Calculation, error)
	Update(*v1.Calculation) (*v1.Calculation, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.Calculation, error)
	List(opts metav1.ListOptions) (*v1.CalculationList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Calculation, err error)
	CalculationExpansion
}

// calculations implements CalculationInterface
type calculations struct {
	client rest.Interface
}

// newCalculations returns a Calculations
func newCalculations(c *CalculationsV1Client) *calculations {
	return &calculations{
		client: c.RESTClient(),
	}
}

// Get takes name of the calculation, and returns the corresponding calculation object, and an error if there is any.
func (c *calculations) Get(name string, options metav1.GetOptions) (result *v1.Calculation, err error) {
	result = &v1.Calculation{}
	err = c.client.Get().
		Resource("calculations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Calculations that match those selectors.
func (c *calculations) List(opts metav1.ListOptions) (result *v1.CalculationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.CalculationList{}
	err = c.client.Get().
		Resource("calculations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested calculations.
func (c *calculations) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("calculations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a calculation and creates it.  Returns the server's representation of the calculation, and an error, if there is any.
func (c *calculations) Create(calculation *v1.Calculation) (result *v1.Calculation, err error) {
	result = &v1.Calculation{}
	err = c.client.Post().
		Resource("calculations").
		Body(calculation).
		Do().
		Into(result)
	return
}

// Update takes the representation of a calculation and updates it. Returns the server's representation of the calculation, and an error, if there is any.
func (c *calculations) Update(calculation *v1.Calculation) (result *v1.Calculation, err error) {
	result = &v1.Calculation{}
	err = c.client.Put().
		Resource("calculations").
		Name(calculation.Name).
		Body(calculation).
		Do().
		Into(result)
	return
}

// Delete takes name of the calculation and deletes it. Returns an error if one occurs.
func (c *calculations) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Resource("calculations").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *calculations) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("calculations").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched calculation.
func (c *calculations) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.Calculation, err error) {
	result = &v1.Calculation{}
	err = c.client.Patch(pt).
		Resource("calculations").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
